### ISSUE TITLE
Group Pomodoros

### ISSUE THREAD

**Issue by han-codes** [andreidimaano/Calcifer#15]
Enhancement request: Group pomodoros where users can be notified together when pomodoros or breaks have ended.
Possibly a command `c: pom pom @user1 @user2 @user3` or users of a specific role `c: pom pom tomatotitans`

**Comment by andreidimaano** [comment]
What do you think about using reacts?

**Comment by han-codes** [comment]
Reactions would be great. How do you think we should use reacts for grouping?
I figured we could have a message that stays pinned that users can react to when they want to do a group pomodoro or can remove their reaction when they don't want to be tagged. I wasn't sure the complexity on your end

**Comment by andreidimaano** [comment]
Ideas:

user types: `c: pom [time] group`
bot responds with starting timer

other users react to timer and will be added to the group pom
everyone will be pinged at the end

Edge Cases:
if the user reacts to a group message but is already in a pom, I can either 
1. ask the user to cancel the current pom
2. remove the reaction from the group pom and tell the user that a pom is already in progress
3. merge the poms - for ex if a user ends a pom in 5 minutes and joins a 50 min pom then the user is attributed x + 45 minutes (x represent previous pom, 45 = 50 group pom - 5 minutes). This is gonna be the hardest way to do this because the user could join like 4 group poms, and there's a lot of math involved with that.

https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-messageReactionAdd

**Comment by han-codes** [comment]
Reacting to the initial timer sounds like a good solution :)

With option 2 if the user reacts to a new group message when already in an existing one, are they pretty much quitting the first group pom automatically and being put in this new one?

I'd say option 1 would be sufficient, like the existing "You're already working!" message when a user tries to start a pom when they've already started one.

**Comment by andreidimaano** [comment]
What should we do if a user wants to cancel a group pom or wants to opt out of a group pom?

**Comment by han-codes** [comment]
> What should we do if a user wants to cancel a group pom or wants to opt out of a group pom?

If the user just removes their reaction, could they be removed from the group and get tagged in a separate bot message saying that they've left?

I personally don't think any one person should be able to cancel the group but if everyone removed their reaction, then I suppose the timer can stop.

Thanks again for looking into this! I'd love to provide more feedback if you'd like :)

**Comment by confuzi** [comment]
> What should we do if a user wants to cancel a group pom or wants to opt out of a group pom?

Might solve the issue or be in combination with the things below, but would a `c: cancel` suffice in terms of removing the reaction for the user? Also could be a good way of just clearing all active poms associated with the user as a fallback.

> If the user just removes their reaction, could they be removed from the group and get tagged in a separate bot message saying that they've left?

So will the reactions from the original message be pushed forward with the later alert messages? Since there's an issue of scrolling up to find the original message in a fast moving chat. Would reacting to any of the alert group poms add the user to the group?

How would the group pom be started after getting finished? would all of the members of the group have the ability to just use c: pom as regular and just have that count for the group?

**Comment by Losstheboss** [comment]
Jumping into this. My thought process is below. Too many perhaps, I know. Just sharing initial thoughts based on what I've read so far.

**Starting pom:**
What about scheduling the pom train to start? I feel this may be cleaner.

Command: c: ptrain 30, pom, 10 
(the minute of the hour. ie if 30, then it'll be 12:30/1:30. If they put 15, then it'd be 12:15/1:15/etc wherever to be consistent), (how long/ pom/ pom pom),  (break time if applicable)... 

I wonder if we can add rounds somehow. Most of us do a 25er, 50er, (sometimes another 50er), and a 25er. Could make a command for the cafe pom where Mayuko typically does a 25/50/25 as a group option?

**Joining pom train:**
Then have a period of time users can react to join the pom? Then at the cutoff point (or do you plan to allow those to join in progress?), the bot will have time to see who reacted and prepare a tag. I've seen bots break when too many reacts occur at once.

**Keeping pom train visible:**
Maybe allow the bot to pin the train message from start to finish? People could just hit the pin button to see the time it started if they're curious. Could also make the bot edit the message itself to update the the time remaining periodically. (IE every 25% of the time.) Then remove the pin after the pom ended.

Another option is to give an if statement if there is an active group pom, count how many new messages appeared from groovy, and after 5 messages, share an update. Something like "Great job Tomato Titans! 15 minutes has passed!" (No tagging to avoid distraction pings)

**Completing pom train:**
The only thing I'm curious about if we can make a rule depending on how many people join the pom, the greater the "YAY YOU DID IT" when the pom is finished. People loved the trains of each individual completion, and it was an epic deal. I think we'd all love that same impact.

**Opting out:**
To opt out, could do react...
Or make a rule that when c: cancel to check if they're in either individual pom or pom train and remove them from either/both.

You can do what I did with one of my bots - send a DM for updates for such things as canceling. Condition to receive that update however would be if they allow messages from random users/bots (meaning they might not get them if they have privacy setting higher), but that would be an option that would avoid too many canceling messages in the cafe, though usually a slight delay.

**Comment by andreidimaano** [comment]
### Trains and Loops
Sadly trains cannot be implemented at the moment. I've tried a couple of ways of having some sort of continuous Pomodoro, however, I cannot implement that feature due to the nature of setTimeout() in a loop. It may also create a memory leak down the line. 
![image](https://user-images.githubusercontent.com/56818175/107414488-eac85b00-6ac6-11eb-9519-ca607bac21e9.png)

I had no idea what a memory leak looked like in Javascript before this project haha. Considering I am dealing with 4 arrays in local memory as well as several setTimeout calls, implementing a train may break the bot. I think I have to rework the bot in order to handle continuous pomodoros :( I'm thinking about switching to setInterval() instead of setTimeout().

### Opting Out
I like your idea of opting out when reacting! I think if I rework the setInterval timer, it may be possible to attribute times from both pomodoro sessions. For now, I think kicking someone out of a session would be good though. I think I have to set up a state diagram for this project in order to capture all the possible states of the timer and the transitions.

### Completing the Pom Train

> "YAY YOU DID IT" when the pom is finished. People loved the trains of each individual completion, and it was an epic deal. I think we'd all love that same impact. 

Could you show me screenshots of this? I'm not entirely sure what this refers to LOL
